# shell history
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000

# command line editing
ZLE_REMOVE_SUFFIX_CHARS=$' \t\n;'

# key bindings
bindkey -v
bindkey '^R' history-incremental-pattern-search-backward    # ctrl-r
bindkey '^[[A' up-line-or-search                            # up-arrow
bindkey '^[[B' down-line-or-search                          # down-arrow
bindkey '^[[Z' reverse-menu-complete                        # shift-tab

# options and extensions
setopt appendhistory autocd extendedglob completealiases
setopt histignoredups histignorespace
setopt interactivecomments

# custom completion scripts
export fpath=(~/.zsh/completions $fpath)

autoload -Uz compinit promptinit
compinit
promptinit

zstyle :compinstall filename '${HOME}/.zshrc'
zstyle ':completion:*' menu select

PROMPT='%Bλ|%2~%#%b '

# set env vars for ls
eval $(dircolors)
export LC_COLLATE=C

# command aliases
alias ls='ls --color=auto --indicator-style=classify --group-directories-first'
alias ll='ls --human-readable -l'
alias la='ll --all'
alias grep='grep --color=auto'
alias xcopy='xsel --clipboard'
alias xpaste='xsel --clipboard'

# export environment variables
export TERM=xterm-256color
export EDITOR=$(which vim)
export PATH=$PATH:$HOME/bin:$HOME/.dotfiles/bin:$HOME/.cargo/bin

source /usr/share/fzf/key-bindings.zsh
source /usr/share/fzf/completion.zsh
