setopt interactive_comments
setopt auto_cd complete_aliases extended_glob
setopt append_history hist_ignore_dups hist_ignore_space

# shell history
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000

# command line editing
autoload -Uz edit-command-line
zle -N edit-command-line
ZLE_REMOVE_SUFFIX_CHARS=$' \t\n;'

# tab completion
autoload -Uz compinit; compinit
zstyle ':completion:*' menu select
fpath=(~/.zfunc $fpath)
typeset -U fpath

# shell prompt
autoload -Uz promptinit; promptinit
if [[ -n "$SSH_CONNECTION" ]]; then
  PROMPT='%B%n@%m|%2~%#%b '
else
  PROMPT='%Bλ|%2~%#%b '
fi

# set env vars for ls
eval $(dircolors)
export LC_COLLATE=C

# environment variables
export EDITOR=$(which nvim)
export LESS='-i -R -F --mouse --wheel-lines=3'
export PATH=$PATH:$HOME/bin:$HOME/.dotfiles/bin:$HOME/.cargo/bin
typeset -U PATH

# key bindings
bindkey -v
bindkey '^R' history-incremental-pattern-search-backward    # ctrl-r
bindkey '^[[A' up-line-or-search                            # up-arrow
bindkey '^[[B' down-line-or-search                          # down-arrow
bindkey '^[[Z' reverse-menu-complete                        # shift-tab
bindkey -M vicmd '^V' edit-command-line                     # ctrl-v

# command aliases
alias ls='ls --color=auto --classify --group-directories-first'
alias ll='ls --human-readable -l'
alias la='ll --all'
alias vim='nvim'
alias vimdiff='nvim -d'
alias edit="$EDITOR"
alias grep='grep --color=auto'
alias pbcopy='wl-copy'
alias pbpaste='wl-paste'

if [[ -x "$(command -v fzf)" ]]; then
  export FZF_DEFAULT_OPTS="--reverse --multi \
    --bind=alt-up:preview-half-page-up \
    --bind=alt-down:preview-half-page-down \
    --bind=ctrl-]:toggle-preview"
  source /usr/share/fzf/key-bindings.zsh
  source /usr/share/fzf/completion.zsh
fi

if [[ -x "$(command -v pyenv)" ]]; then
  eval "$(pyenv init -)"
fi

if [[ -f /opt/miniconda3/etc/profile.d/conda.sh ]]; then
  source /opt/miniconda3/etc/profile.d/conda.sh
fi

load-nvm() {
  source /usr/share/nvm/init-nvm.sh
}

open() {
  xdg-open "$@" &!
}
