setopt interactive_comments
setopt auto_cd complete_aliases extended_glob
setopt append_history hist_ignore_dups hist_ignore_space

# shell history
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000

# command line editing
autoload -Uz edit-command-line
zle -N edit-command-line

ZLE_REMOVE_SUFFIX_CHARS=$' \t\n;'

# tab completion
fpath=(~/.zfunc $fpath)
typeset -U fpath

autoload -Uz compinit
compinit

zstyle ':completion:*' menu select

# shell prompt
autoload -Uz promptinit
promptinit

if [[ -n "$SSH_CONNECTION" ]]; then
  PROMPT='%B%n@%m|%2~%#%b '
else
  PROMPT='%Bλ|%2~%#%b '
fi

# set env vars for ls
eval $(dircolors)
export LC_COLLATE=C

# environment variables
export TERM=xterm-256color
export EDITOR=$(which vim)
export PATH=$PATH:$HOME/bin:$HOME/.dotfiles/bin:$HOME/.cargo/bin
typeset -U PATH

# key bindings
bindkey -v
bindkey '^R' history-incremental-pattern-search-backward    # ctrl-r
bindkey '^[[A' up-line-or-search                            # up-arrow
bindkey '^[[B' down-line-or-search                          # down-arrow
bindkey '^[[Z' reverse-menu-complete                        # shift-tab
bindkey -M vicmd '^V' edit-command-line

# command aliases
alias ls='ls --color=auto --classify --group-directories-first'
alias ll='ls --human-readable -l'
alias la='ll --all'
alias grep='grep --color=auto'
alias pbcopy='xsel --clipboard'
alias pbpaste='xsel --clipboard'

source /usr/share/fzf/key-bindings.zsh
source /usr/share/fzf/completion.zsh
