" vim config file "

" make vim more useful!
set nocompatible

" Vundle plugin manager
filetype off
set rtp+=~/.vim/bundle/Vundle.vim

call vundle#begin()
" core
Plugin 'gmarik/Vundle.vim'
Plugin 'bling/vim-airline'
" essential
Plugin 'majutsushi/tagbar'
Plugin 'ctrlpvim/ctrlp.vim'
Plugin 'scrooloose/nerdtree'
Plugin 'jlanzarotta/bufexplorer'
" autocompletion
Plugin 'ervandew/supertab'
Plugin 'scrooloose/syntastic'
Plugin 'racer-rust/vim-racer'
Plugin 'artur-shaik/vim-javacomplete2'
" external
Plugin 'benmills/vimux'
Plugin 'tpope/vim-fugitive'
" editing
Plugin 'tpope/vim-surround'
Plugin 'scrooloose/nerdcommenter'
Plugin 'editorconfig/editorconfig-vim'
" language support
Plugin 'dag/vim-fish'
Plugin 'rust-lang/rust.vim'
Plugin 'vim-ruby/vim-ruby'
Plugin 'pangloss/vim-javascript'
Plugin 'gabrielelana/vim-markdown'
Plugin 'jrozner/vim-antlr'
Plugin 'cespare/vim-toml'
Plugin 'ap/vim-css-color'
call vundle#end()

filetype plugin indent on
syntax on

" vim behavior
set title               " change terminal title
set number              " set line numbering
set hidden              " hide buffers instead of closing
set mouse=a             " enable mouse
set scrolloff=5         " keep lines above and below cursor
set autoread            " refresh when file is changed outside
set spelllang=en_us     " set spelling language to English
colorscheme teal

" searching
set hlsearch            " highlight search terms
set incsearch           " show search matches as you type
set ignorecase          " case insensitive search
set smartcase           " case sensitive when uppercase present

" tab settings
set autoindent expandtab
set tabstop=4 shiftwidth=4 softtabstop=4
autocmd filetype ruby,javascript,json,html,css,scss,yaml,liquid,xml
  \ set tabstop=2 shiftwidth=2 softtabstop=2

" vim 256 colors
if $TERM == 'xterm-256color' || $TERM == 'screen-256color' || $COLORTERM == 'gnome-terminal'
  set t_Co=256
endif

" enable ruby autocompletion
autocmd FileType ruby,eruby let g:rubycomplete_buffer_loading = 1
autocmd FileType ruby,eruby let g:rubycomplete_classes_in_global = 1
autocmd FileType ruby,eruby let g:rubycomplete_rails = 1

" enable java autocompletion
autocmd FileType java setlocal omnifunc=javacomplete#Complete

" vim-airline config
set laststatus=2
let g:airline#extensions#tabline#enabled = 1

if !exists('g:airline_symbols')
  " unicode symbols
  let g:airline_symbols = {}
  let g:airline_left_sep = ''
  let g:airline_right_sep = ''
  let g:airline_symbols.spell = '⚐'
  let g:airline_symbols.paste = 'ρ'
  let g:airline_symbols.branch = '⎇ '
  let g:airline_symbols.linenr = '¶'
  let g:airline_symbols.maxlinenr = ''
  let g:airline_symbols.whitespace = 'Ξ'
endif

" supertab config
let g:SuperTabDefaultCompletionType = 'context'
let g:SuperTabClosePreviewOnPopupClose = 1

" syntastic config
let g:syntastic_auto_loc_list = 1
"let g:syntastic_rust_checkers = ['rustc']
"let g:syntastic_rust_checkers = ['cargo']

" vim-racer config
let g:racer_experimental_completer = 1

" markdown config
let g:markdown_enable_input_abbreviations = 0

" vimux config
let g:VimuxOrientation = "h"
let g:VimuxPromptString = "vimux$ "

" key mapping leader
let mapleader = '\'

" window navigation
nnoremap <S-h> <C-w>h
nnoremap <S-j> <C-w>j
nnoremap <S-k> <C-w>k
nnoremap <S-l> <C-w>l

" buffer navigation
nmap <C-h> :bprevious<CR>
nmap <C-l> :bnext<CR>
nmap <C-x> :bdelete<CR>

" key mappings
nnoremap j gj
nnoremap k gk

" leader mappings
nnoremap <leader>a ggvG$
nmap <leader>q :quit<CR>
nmap <leader>w :write<CR>
nmap <leader>p :set paste!<CR>
nmap <leader>e :edit <C-r>=expand('%:p:h')<CR>/

" highlight mappings
nmap <leader>hc :nohlsearch<CR>

" split mappings
nmap <leader>sh :split<Space>
nmap <leader>sv :vsplit<Space>

" buffer mappings
nmap <leader>bf :bfirst<CR>
nmap <leader>bl :blast<CR>

" rust lookup mappings
nmap <leader>rd <Plug>(rust-doc)
nmap <leader>rf <Plug>(rust-def)
nmap <leader>rs <Plug>(rust-def-split)
nmap <leader>rv <Plug>(rust-def-vertical)

" vimux mappings
nmap <leader>vx :VimuxPromptCommand<CR>
nmap <leader>vl :VimuxRunLastCommand<CR>
nmap <leader>vk :VimuxInterruptRunner<CR>
nmap <leader>vv :VimuxInspectRunner<CR>
nmap <leader>vz :VimuxZoomRunner<CR>
nmap <leader>vc :VimuxClearRunnerHistory<CR>
nmap <leader>vq :VimuxCloseRunner<CR>

" fn mappings
nmap <F2> :BufExplorerHorizontalSplit<CR>
nmap <F3> :NERDTreeToggle<CR>
nmap <F4> :TagbarToggle<CR>
nmap <F5> :edit<CR>
nmap <F8> :set mouse=a<CR>
nmap <F9> :set mouse=""<CR>
nmap <F12> :set spell!<CR>
