HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000

ZLE_REMOVE_SUFFIX_CHARS=$' \t\n;'

bindkey -v
bindkey '^R' history-incremental-pattern-search-backward
bindkey '^[[A' up-line-or-search
bindkey '^[[B' down-line-or-search
bindkey '^[[Z' reverse-menu-complete

setopt appendhistory autocd extendedglob completealiases
setopt HIST_IGNORE_DUPS INTERACTIVE_COMMENTS

autoload -Uz compinit promptinit
compinit
promptinit

zstyle :compinstall filename '${HOME}/.zshrc'
zstyle ':completion:*' menu select

alias ls='ls --color=auto'
alias grep='grep --color=auto'

PROMPT='%B|%n@%m:%2~|%#%b '

# export environment variables
export PATH=$HOME/.dotfiles/bin:$PATH
export EDITOR=$(which vim)
export TERM=xterm-256color
export RUST_SRC_PATH=/usr/src/rust/src
export PATH="$PATH:$HOME/.rvm/bin:$HOME/.cabal/bin:$HOME/.cargo/bin"

# Load RVM into a shell session *as a function*
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"
