# shell history
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000

# command line editing
ZLE_REMOVE_SUFFIX_CHARS=$' \t\n;'

# key bindings
bindkey -v
bindkey '^R' history-incremental-pattern-search-backward    # ctrl-r
bindkey '^[[A' up-line-or-search                            # up-arrow
bindkey '^[[B' down-line-or-search                          # down-arrow
bindkey '^[[Z' reverse-menu-complete                        # shift-tab

# options and extensions
setopt appendhistory autocd extendedglob completealiases
setopt histignoredups histignorespace
setopt interactivecomments

# custom completion scripts
export fpath=(~/.zsh/completion $fpath)

autoload -Uz compinit promptinit
compinit
promptinit

zstyle :compinstall filename '${HOME}/.zshrc'
zstyle ':completion:*' menu select

PROMPT='%B|%n@%m:%2~|%#%b '

# command aliases
alias ls='ls --color=auto'
alias la='ls --color=auto -a'
alias ll='ls --color=auto -lh'
alias lla='ls --color=auto -lha'
alias grep='grep --color=auto'

# export environment variables
export TERM=screen-256color
export EDITOR=$(which vim)
export PATH=$PATH:$HOME/.dotfiles/bin:$HOME/.cargo/bin
