" vim config file "

" make vim more useful!
set nocompatible

" Vundle plugin manager
filetype off
set rtp+=~/.vim/bundle/Vundle.vim

call vundle#begin()
Plugin 'gmarik/Vundle.vim'
Plugin 'bling/vim-airline'
Plugin 'scrooloose/nerdtree'
Plugin 'scrooloose/syntastic'
Plugin 'majutsushi/tagbar'
Plugin 'tpope/vim-fugitive'
Plugin 'kien/ctrlp.vim'
Plugin 'ap/vim-css-color'
Plugin 'scrooloose/nerdcommenter'
Plugin 'ervandew/supertab'
Plugin 'gabrielelana/vim-markdown'
Plugin 'rust-lang/rust.vim'
Plugin 'cespare/vim-toml'
call vundle#end()

filetype plugin indent on
syntax on

" vim behavior
set title               " change terminal title
set number              " set line numbering
set hidden              " hide buffers instead of closing
set mouse=a             " enable mouse
set scrolloff=5         " keep lines above and below cursor
set autoread            " refresh when file is changed outside
set spelllang=en_us     " set spelling language to English
set background=dark

" searching
set hlsearch            " highlight search terms
set incsearch           " show search matches as you type
set ignorecase          " case insensitive search
set smartcase           " case sensitive when uppercase present

" tab settings
set autoindent expandtab
set tabstop=2 shiftwidth=2 softtabstop=2
autocmd filetype c,cpp,python,perl set tabstop=4 shiftwidth=4 softtabstop=4

" enable native syntax highlight for markdown with .md extension
autocmd BufNewFile,BufRead *.md set filetype=markdown

" kick vim into 256 colors
if $TERM == "xterm-256color" || $TERM == "screen-256color" || $COLORTERM == "gnome-terminal"
  set t_Co=256
endif

" vim-airline config
set laststatus=2
let g:airline#extensions#tabline#enabled = 1

if !exists('g:airline_symbols')
  let g:airline_symbols = {}
endif

" unicode symbols
let g:airline_left_sep = '▶'
let g:airline_right_sep = '◀'
let g:airline_symbols.linenr = '¶'
let g:airline_symbols.branch = '⎇ '
let g:airline_symbols.paste = 'ρ'
let g:airline_symbols.whitespace = 'Ξ'

" key mappings
let mapleader = '\'

" clear search highlights
nmap <leader>ch :nohlsearch<CR>

" window navigation
nnoremap <S-h> <C-w>h
nnoremap <S-j> <C-w>j
nnoremap <S-k> <C-w>k
nnoremap <S-l> <C-w>l

" tab settings
nmap <leader>e :tabprevious<CR>
nmap <leader>r :tabnext<CR>
nmap <leader>t :tabedit <C-r>=expand("%:p:h")<CR>/

" buffer settings
nmap <leader>b :buffers<CR>
nmap <C-b> :bprevious<CR>
nmap <C-n> :bnext<CR>
nmap <C-d> :NERDTreeClose<CR>:TagbarClose<CR>:bdelete<CR>
nmap <C-e> :edit <C-r>=expand("%:p:h")<CR>/

" key mappings
nnoremap j gj
nnoremap k gk
nnoremap <leader>a ggvG$
nmap <F5> :edit<CR>
nmap <F8> :set mouse=a<CR>
nmap <F9> :set mouse=""<CR>
nmap <F12> :set spell!<CR>
nmap <leader>p :set paste!<CR>
nmap <leader>w :write<CR>
nmap <leader>q :quit<CR>

" plugin mappings
nmap <F3> :NERDTreeToggle<CR>
nmap <F4> :TagbarToggle<CR>
