HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000

EDITOR=$(which vim)
TERM=xterm-256color
PATH=$PATH:$HOME/.rvm/bin

bindkey -v
bindkey '^R' history-incremental-pattern-search-backward
bindkey '^[[A' up-line-or-search
bindkey '^[[B' down-line-or-search

setopt appendhistory autocd extendedglob completealiases
setopt HIST_IGNORE_DUPS INTERACTIVE_COMMENTS

autoload -Uz compinit promptinit
compinit
promptinit

zstyle :compinstall filename '${HOME}/.zshrc'
zstyle ':completion:*' menu select

alias ls='ls --color=auto'
alias grep='grep --color=auto'

PROMPT='%B|%n@%m:%2~|%#%b '

# Load RVM into a shell session *as a function*
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"
